# -*- coding: utf-8 -*-
"""pandas practice .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuWEWD6wb_-0o2oQwUobtOFkjaQPQpgW
"""

import pandas as pd
import numpy as np

# Specify the full path to your Excel file in Google Drive
# Example: '/content/drive/MyDrive/folder_name/churn.xlsx'
excel_file_path = '/content/drive/MyDrive/churn.xlsx'  # Update this path if your file is in a subfolder

try:
    df_churn = pd.read_excel(excel_file_path)
    print("Excel file loaded successfully!")
    print(df_churn.head())
except FileNotFoundError:
    print(f"Error: The file at '{excel_file_path}' was not found. Please check the path.")
except Exception as e:
    print(f"An error occurred while loading the Excel file: {e}")

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')

df.head()

df.tail()

df.info()

df.describe()

df.columns

df.T  #TRanspose row becomes column and column becomes row

new_df=df.sort_values('Age')

new_df.head(5) #By using this and upper code we firstly sort age & then check the top or last 5 rows

#print perticular  column
df['Age']

df['Balance']

#new column by Adding 1k in each row
df['new Balance']=df['Balance']+1000
df['new Balance']

df['new Balance'].head(5)

#Creat one more column with same data like
df['random day']='i m sheikh'
df.head()

#Accesssing Rows
df[11:15]

new_c=df[df.Age>50] #This is where class like select * from Age where Age>50
new_c.head()

len(df['Age'])

len(new_c) #Values Those having Age more then 50

df.isnull().sum()

"""There is no null values in my dataset but if we have then we write suppose in age column

df['Age'].fillna(10)  

null values will be replace with 10.
"""

#Remove Columns
df.pop('RowNumber')

df.head()

df['Age']

#using Special functions like :
df[' Age Square Root']=df['Age'].apply(np.sqrt)

# OR if i says square then?
df['Age Square']=df['Age'].apply(np.square)

df.head()

#FOR drooping null Values
df['Age'].dropna()

